title: Ted Meralus
description: > # this means to ignore newlines until "baseurl:"
  The blogs and thoughts of Tedley Meralus.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: techdadteddy #if your site has a twitter account, enter it here

# Author Settings
author: Tedley Meralus # add your name
author-img: moneyshot.png # add your photo
about-author: An investment in knowledge pays the best interest.
#about-author: I', currently focused on open source development and documenting my journey as I go. # add description
#about-author: I provide freelance services for open source software, web development, linux based troubleshooting, cloud and IT consulting, and more. Documenting my journey as I go. # add description
social-twitter: techdadteddy # add your Twitter handle
#social-facebook: tmeralus # add your Facebook handle
social-github: tedleyem # add your Github handle
social-linkedin: tmeralus # add your Linkedin handle
home-link: meralus.com 
project-link: links.meralus.com
project-tech: tedley.square.site

social-email: tmeralus@gmail.com # add your Email address

# Disqus
# discus-identifier: techdadteddy # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed 
  - jekyll-relative-links

paginate: 8
paginate_path: "/page/:num"

relative_links:
  enabled:     false
  collections: false
  
relative_links:
  exclude:
    - directory
    - file.md

exclude: 
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
  - vendor 