# ICONS can be found here
# https://iconify.design/
# https://icon-sets.iconify.design/?category=General

- category: Projects
  items:
    - title: Python Projects
      url:  https://meralus.com/
      icon: uiw:linux
      text: PlaceHolder

    - title: Terraform Projects
      url:  https://meralus.com/
      icon: carbon:logo-red-hat-ansible
      text: PlaceHolder

    - title: Ansbile Automation Projects
      url:  https://meralus.com/
      icon: carbon:logo-red-hat-ansible
      text: PlaceHolder

    - title: Managed Docker Apps
      url:  https://meralus.com/
      icon: carbon:logo-red-hat-ansible
      text: PlaceHolder 

    - title: Ansbile Automation Services
      url:  https://meralus.com/
      icon: carbon:logo-red-hat-ansible
      text: PlaceHolder



- category: Services
  items:
    - title: Linux Consulting Services
      url:  https://meralus.com/
      icon: uiw:linux
      text: PlaceHolder

    - title: Ansbile Automation Services
      url:  https://meralus.com/
      icon: carbon:logo-red-hat-ansible
      text: PlaceHolder

    - title: Infrastructure Managed Services
      url:  https://meralus.com/
      icon: streamline:industry-innovation-and-infrastructure-solid
      text: PlaceHolder

    - title: High Availability Consulting
      url:  https://meralus.com/
      icon: oui:app-uptime
      text: PlaceHolder

    - title: SAAS Consulting
      url:  https://meralus.com/
      icon: carbon:container-software
      text: PlaceHolder

    - title: Devops Consulting
      url:  https://meralus.com/
      icon: mdi:infinity-box
      text: PlaceHolder

    - title: Scripting/Programming Services
      url:  https://meralus.com/
      icon: solar:programming-linear
      text: PlaceHolder